language: ruby
rvm:
  - 1.9.3
before_script:
  - sudo apt-get install zsh
install: gem install tf -v '>=0.4.1'
script: find core/ -name '*_comment_test.sh' | xargs tf --text
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
  email:
    recipients:
      - mpapis@gmail.com
    on_failure: change

